var importConfig = {"area":140,"type":2,"hasInvertor":true,"panelCount":1,"houseArea":"200","powerConsumption":"2","tokens":[{"type":0,"tiles":[{"column":0,"row":0}],"startTile":{"row":0,"column":0}},{"type":1,"tiles":[{"row":0,"column":1}],"startTile":{"row":0,"column":1}},{"type":0,"tiles":[{"column":2,"row":0}],"startTile":{"row":0,"column":2}},{"type":0,"tiles":[{"column":3,"row":0}],"startTile":{"row":0,"column":3}},{"type":0,"tiles":[{"column":4,"row":0}],"startTile":{"row":0,"column":4}},{"type":0,"tiles":[{"column":5,"row":0}],"startTile":{"row":0,"column":5}},{"type":0,"tiles":[{"column":6,"row":0}],"startTile":{"row":0,"column":6}},{"type":0,"tiles":[{"column":7,"row":0}],"startTile":{"row":0,"column":7}},{"type":0,"tiles":[{"column":8,"row":0}],"startTile":{"row":0,"column":8}},{"type":0,"tiles":[{"column":9,"row":0}],"startTile":{"row":0,"column":9}},{"type":0,"tiles":[{"column":10,"row":0}],"startTile":{"row":0,"column":10}},{"type":0,"tiles":[{"column":11,"row":0}],"startTile":{"row":0,"column":11}},{"type":0,"tiles":[{"column":0,"row":1}],"startTile":{"row":1,"column":0}},{"type":0,"tiles":[{"column":1,"row":1}],"startTile":{"row":1,"column":1}},{"type":0,"tiles":[{"column":2,"row":1}],"startTile":{"row":1,"column":2}},{"type":0,"tiles":[{"column":3,"row":1}],"startTile":{"row":1,"column":3}},{"type":0,"tiles":[{"column":4,"row":1}],"startTile":{"row":1,"column":4}},{"type":0,"tiles":[{"column":5,"row":1}],"startTile":{"row":1,"column":5}},{"type":0,"tiles":[{"column":6,"row":1}],"startTile":{"row":1,"column":6}},{"type":0,"tiles":[{"column":7,"row":1}],"startTile":{"row":1,"column":7}},{"type":0,"tiles":[{"column":8,"row":1}],"startTile":{"row":1,"column":8}},{"type":0,"tiles":[{"column":9,"row":1}],"startTile":{"row":1,"column":9}},{"type":0,"tiles":[{"column":10,"row":1}],"startTile":{"row":1,"column":10}},{"type":0,"tiles":[{"column":11,"row":1}],"startTile":{"row":1,"column":11}},{"type":0,"tiles":[{"column":0,"row":2}],"startTile":{"row":2,"column":0}},{"type":0,"tiles":[{"column":1,"row":2}],"startTile":{"row":2,"column":1}},{"type":0,"tiles":[{"column":2,"row":2}],"startTile":{"row":2,"column":2}},{"type":0,"tiles":[{"column":3,"row":2}],"startTile":{"row":2,"column":3}},{"type":0,"tiles":[{"column":4,"row":2}],"startTile":{"row":2,"column":4}},{"type":0,"tiles":[{"column":5,"row":2}],"startTile":{"row":2,"column":5}},{"type":0,"tiles":[{"column":6,"row":2}],"startTile":{"row":2,"column":6}},{"type":0,"tiles":[{"column":7,"row":2}],"startTile":{"row":2,"column":7}},{"type":0,"tiles":[{"column":8,"row":2}],"startTile":{"row":2,"column":8}},{"type":0,"tiles":[{"column":9,"row":2}],"startTile":{"row":2,"column":9}},{"type":0,"tiles":[{"column":10,"row":2}],"startTile":{"row":2,"column":10}},{"type":0,"tiles":[{"column":11,"row":2}],"startTile":{"row":2,"column":11}}]};
		

$(document).ready(function(){
	initDiy();
});



